---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 2.3.1
  - 2.2.4
  - 2.1.9
  - 2.0.0
  - 1.9.3
script: "bundle exec rake validate"
env:
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" 
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
  - PUPPET_GEM_VERSION="~> 4.3.0"
  - PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.6.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.6.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.8.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.6.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.1.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.3.0"
